version: '3.1'
services:
  app:
    build: .
    ports:
     - "3000:3000"
    command: tail -F anything
    volumes:
     - ./app:/usr/src/app/
    links:
     - db
  db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: example
