# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc8cadc9aa0a8d1596f9134489e7d68725326bd3104193435ff970fc82c5dff1a47211b2ef93d148db41e09a86789a837f46309950420f62b8828f788d79e8e1

test:
  secret_key_base: 1dc5208a412017bc9fbc1020a4f0cd51312f6794147d277d16c6b413b1a71d380353b6696178e4330810f655126ebb09f938373248ff8826731c2e88ae97f8e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
